# stubs for the IDE to provide autocompletion.
def from_int8(int) -> bytes: ...
def to_int8(bytes) -> int: ...
def from_uint8(int) -> bytes: ...
def to_uint8(bytes) -> int: ...

def from_int16(int) -> bytes: ...
def to_int16(bytes) -> int: ...
def from_uint16(int) -> bytes: ...
def to_uint16(bytes) -> int: ...

def from_int32(int) -> bytes: ...
def to_int32(bytes) -> int: ...
def from_uint32(int) -> bytes: ...
def to_uint32(bytes) -> int: ...

def from_int64(int) -> bytes: ...
def to_int64(bytes) -> int: ...
def from_uint64(int) -> bytes: ...
def to_uint64(bytes) -> int: ...

def from_float32(float) -> bytes: ...
def to_float32(bytes) -> float: ...
def from_float4(float) -> bytes: ...
def to_float4(bytes) -> float: ...
